apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "solr.security-config-map" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "solr.labels" . | indent 4 | trim }}
data:
 security.json: |
   {
   "authentication":{
      "blockUnknown": true,
      "class":"solr.BasicAuthPlugin",
      "credentials":{"solradmin":"UjnAsHqXA4lXYTX316MLVK580FhLQhBQUFH80e9ENCY= CewINMgTUzAbYnoe/QP6AGlA6S1dJE5sbm7BQFxKROU="}
   },
   "authorization":{
      "class":"solr.RuleBasedAuthorizationPlugin",
      "permissions":[{"name":"security-edit",
   	  "role":"admin"}],
      "user-role":{"solradmin":"admin"}
   }}
