apiVersion: v1
kind: Secret
metadata:
  name: {{ template "solr.credentials-security-config-map" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "solr.labels" . | indent 4 | trim }}
type: Opaque
data:
  password: {{ .Values.password | b64enc }}