{{- if eq (.Values.loadBalancer | lower) "enabled" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "solr.loadbalancer-service-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "solr.labels" . | indent 4 | trim }}
spec:
  ports:
  - port: {{ .Values.loadBalancerPort }}
    targetPort: solr
    name: solr
  selector:
    {{ include "solr.selector" . | indent 4 | trim }}
  type: LoadBalancer
{{- end }}