apiVersion: v1
kind: ConfigMap
metadata:
  name: solr-start
data:
 startsolr.sh: |
   #prepare ZK path and copy solr.xml and security.json
   /opt/solr/server/scripts/cloud-scripts/zkcli.sh -cmd ls ${ZKPATH} -zkhost ${ZK_HOST} > /dev/null 2>&1 \
   || \
   ( \
   /opt/solr/server/scripts/cloud-scripts/zkcli.sh -cmd makepath ${ZKPATH} -zkhost ${ZK_HOST} \
   && \
   /opt/solr/server/scripts/cloud-scripts/zkcli.sh -cmd putfile ${ZKPATH}/solr.xml /opt/solr/server/solr/solr.xml -zkhost ${ZK_HOST} \
   && \
   /opt/solr/server/scripts/cloud-scripts/zkcli.sh -cmd putfile ${ZKPATH}/security.json /opt/solr/${SOLR_INSTNAME}/security.json  -zkhost ${ZK_HOST} \
   )


   # define hostname for solr
   export SOLR_HOST="`uname -n | fgrep -f - /etc/hosts | awk '{print $2}' | cut -d'.' -f1-3`"

   # and OPTS
   export SOLR_OPTS="$SOLR_OPTS $SOLR_ZK_CREDS_AND_ACLS -Dsolr.solr.instname=${SOLR_INSTNAME}"

   #start solr
   exec solr start -c -zkhost ${ZK_HOST}${ZKPATH} -f
---