apiVersion: v1
kind: Secret
metadata:
  name: {{ template "solr.acl-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "solr.labels" . | indent 4 | trim }}
type: Opaque
stringData:
  zk-acl: "-DzkACLProvider=org.apache.solr.common.cloud.VMParamsAllAndReadonlyDigestZkACLProvider -DzkCredentialsProvider=org.apache.solr.common.cloud.VMParamsSingleSetCredentialsDigestZkCredentialsProvider -DzkDigestUsername={{ .Values.zookeeper.user }} -DzkDigestPassword={{ .Values.zookeeper.password }}"